CREATE TABLE agents (
    id BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY CONSTRAINT agents_pk PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    sp_power VARCHAR(255) NOT NULL,
    alive BOOLEAN NOT NULL,
    rank INT NOT NULL
);


CREATE TABLE assignments (
    id BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY CONSTRAINT assignments_pk PRIMARY KEY,
    mission_id BIGINT NOT NULL,
    agent_id BIGINT NOT NULL,
    starting DATE NOT NULL,
    ending DATE
);

CREATE TABLE missions (
    id BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY CONSTRAINT missions_pk PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    task VARCHAR(255) NOT NULL,
    place VARCHAR(255) NOT NULL,
    suc BOOLEAN NOT NULL,
    fin BOOLEAN NOT NULL,
    min_ag_rank INT NOT NULL
);
